### ISSUE TITLE
QuerySelector does not find class names with line breaks

### ISSUE THREAD

**Issue by shravan2x** [atifaziz/Hazz#22] opened 2021-01-29 05:55 UTC
I have to parse and query HTML that's formatted badly with line breaks in class attributes. This library does not appear to support those however:

```c#
string html = @"<html><body><div class=""class_1""><span class=""class_2
 class_3"">Text</span></body></html>";
HtmlDocument htmldom = new HtmlDocument();
htmldom.LoadHtml(html);

Console.WriteLine(JsonConvert.SerializeObject(htmldom.DocumentNode.QuerySelector(".class_1").FirstChild.GetClasses())); // Prints classes correctly
Console.WriteLine(htmldom.DocumentNode.QuerySelector(".class_1 > .class_2")); // Prints null
```

It works fine when the line break is removed.

**Comment by shravan2x** [comment] 2021-02-05 09:09
Actually this has been resolved in master way back in April 2020. When will 1.3.0 be out?

**Comment by atifaziz** [comment] 2021-02-06 16:17
Duplicate of #15.

**Closed as completed by atifaziz** 2021-02-06 16:17 UTC
Labels: duplicate
